name: test

on:
  push:
    branches:
      - master
    tags:
      - 'release-frontend'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "release the frontend"
